name: settings
definition:
  # Wires connect to data in collections
  wires:
    leadsources:
      collection: uesio/crm.lead_source
      fields:
        uesio/crm.api_name:
        uesio/crm.label:
        uesio/crm.active:
    opportunitystages:
      collection: uesio/crm.opportunity_stage
      fields:
        uesio/crm.api_name:
        uesio/crm.label:
        uesio/crm.active:
  # Components determine the layout and composition of your view
  components:
    - uesio/io.viewlayout:
        left:
          - uesio/crm.nav:
        content:
          - uesio/io.titlebar:
              uesio.variant: uesio/crm.main
              title: Settings
              subtitle: Personalize ues.io CRM for your organization.
              avatar:
                - uesio/io.text:
                    uesio.variant: uesio/io.icon
                    text: settings
          - uesio/io.box:
              uesio.variant: uesio/crm.primarysection
              components:
                - uesio/io.tabs:
                    tabs:
                      - id: leadsources
                        label: Lead Sources
                        components:
                          - uesio/io.grid:
                              uesio.variant: uesio/crm.three_columns
                              items:
                                - uesio/io.box:
                                    uesio.styleTokens:
                                      root:
                                        - lg:col-span-2
                                        - lg:order-first
                                        - order-last
                                    components:
                                      - uesio/io.table:
                                          uesio.variant: uesio/crm.main
                                          columns:
                                            - field: uesio/crm.api_name
                                            - field: uesio/crm.label
                                            - field: uesio/crm.active
                                          uesio.id: leadsources
                                          mode: READ
                                          wire: leadsources
                                          pagesize: 10
                                - uesio/io.box:
                                    components:
                                      - uesio/io.titlebar:
                                          title:
                                          uesio.variant: uesio/crm.sub_noborder
                                          actions:
                                            - uesio/io.toolbar:
                                                linkedComponentId: leadsources
                                                linkedComponentType: uesio/io.table
                                                right:
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: wire/SAVE
                                                          wires:
                                                            - leadsources
                                                      text: $Label{uesio/io.save}
                                                      hotkey: "meta+s"
                                                      uesio.variant: uesio/crm.primary
                                                      uesio.display:
                                                        - type: wireHasChanges
                                                          wire: leadsources
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: wire/CREATE_RECORD
                                                          wire: leadsources
                                                          prepend: true
                                                        - signal: component/CALL
                                                          component: uesio/io.table
                                                          componentsignal: SET_EDIT_MODE
                                                          targettype: specific
                                                          componentid: leadsources
                                                      text: $Label{uesio/io.create}
                                                      uesio.variant: uesio/crm.primary
                                                      uesio.styleTokens:
                                                        root:
                                                          - bg-emerald-600
                                                          - border-emerald-600
                                                      uesio.display:
                                                        - type: mergeValue
                                                          value: EDIT
                                                          sourceValue: $ComponentState{[uesio/io.table][leadsources][mode]}
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: wire/CANCEL
                                                          wire: leadsources
                                                        - signal: component/CALL
                                                          component: uesio/io.table
                                                          componentsignal: SET_READ_MODE
                                                          targettype: specific
                                                          componentid: leadsources
                                                      uesio.display:
                                                        - type: group
                                                          conjunction: OR
                                                          conditions:
                                                            - type: wireHasChanges
                                                              wire: leadsources
                                                            - type: mergeValue
                                                              value: EDIT
                                                              sourceValue: $ComponentState{[uesio/io.table][leadsources][mode]}
                                                      text: $Label{uesio/io.cancel}
                                                      uesio.variant: uesio/crm.secondary
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: component/CALL
                                                          component: uesio/io.table
                                                          componentsignal: TOGGLE_MODE
                                                          targettype: specific
                                                          componentid: leadsources
                                                      text: Edit
                                                      icon: edit_square
                                                      iconFill: false
                                                      uesio.variant: uesio/crm.secondary
                                                      uesio.display:
                                                        - type: mergeValue
                                                          value: EDIT
                                                          operator: NOT_EQUALS
                                                          sourceValue: $ComponentState{[uesio/io.table][leadsources][mode]}
                                      - uesio/io.box:
                                          uesio.variant: uesio/crm.note
                                          components:
                                            - uesio/io.text:
                                                text: Specify the valid lead sources for your organization. A lead source is where the data for a lead originated.
                                      - uesio/io.box:
                                          uesio.variant: uesio/crm.note
                                          components:
                                            - uesio/io.text:
                                                text: Only active lead sources will appear when selecting a source for a new lead.
                      - id: opportunitystages
                        label: Opportunity Stages
                        components:
                          - uesio/io.grid:
                              uesio.variant: uesio/crm.three_columns
                              items:
                                - uesio/io.box:
                                    uesio.styleTokens:
                                      root:
                                        - lg:col-span-2
                                        - lg:order-first
                                        - order-last
                                    components:
                                      - uesio/io.table:
                                          uesio.variant: uesio/crm.main
                                          columns:
                                            - field: uesio/crm.api_name
                                            - field: uesio/crm.label
                                            - field: uesio/crm.active
                                          uesio.id: opportunitystages
                                          mode: READ
                                          wire: opportunitystages
                                          pagesize: 10
                                - uesio/io.box:
                                    components:
                                      - uesio/io.titlebar:
                                          title:
                                          uesio.variant: uesio/crm.sub_noborder
                                          actions:
                                            - uesio/io.toolbar:
                                                linkedComponentId: opportunitystages
                                                linkedComponentType: uesio/io.table
                                                right:
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: wire/SAVE
                                                          wires:
                                                            - opportunitystages
                                                      text: $Label{uesio/io.save}
                                                      hotkey: "meta+s"
                                                      uesio.variant: uesio/crm.primary
                                                      uesio.display:
                                                        - type: wireHasChanges
                                                          wire: opportunitystages
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: wire/CREATE_RECORD
                                                          wire: opportunitystages
                                                          prepend: true
                                                        - signal: component/CALL
                                                          component: uesio/io.table
                                                          componentsignal: SET_EDIT_MODE
                                                          targettype: specific
                                                          componentid: opportunitystages
                                                      text: $Label{uesio/io.create}
                                                      uesio.variant: uesio/crm.primary
                                                      uesio.styleTokens:
                                                        root:
                                                          - bg-emerald-600
                                                          - border-emerald-600
                                                      uesio.display:
                                                        - type: mergeValue
                                                          value: EDIT
                                                          sourceValue: $ComponentState{[uesio/io.table][opportunitystages][mode]}
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: wire/CANCEL
                                                          wire: opportunitystages
                                                        - signal: component/CALL
                                                          component: uesio/io.table
                                                          componentsignal: SET_READ_MODE
                                                          targettype: specific
                                                          componentid: opportunitystages
                                                      uesio.display:
                                                        - type: group
                                                          conjunction: OR
                                                          conditions:
                                                            - type: wireHasChanges
                                                              wire: opportunitystages
                                                            - type: mergeValue
                                                              value: EDIT
                                                              sourceValue: $ComponentState{[uesio/io.table][opportunitystages][mode]}
                                                      text: $Label{uesio/io.cancel}
                                                      uesio.variant: uesio/crm.secondary
                                                  - uesio/io.button:
                                                      signals:
                                                        - signal: component/CALL
                                                          component: uesio/io.table
                                                          componentsignal: TOGGLE_MODE
                                                          targettype: specific
                                                          componentid: opportunitystages
                                                      text: Edit
                                                      icon: edit_square
                                                      iconFill: false
                                                      uesio.variant: uesio/crm.secondary
                                                      uesio.display:
                                                        - type: mergeValue
                                                          value: EDIT
                                                          operator: NOT_EQUALS
                                                          sourceValue: $ComponentState{[uesio/io.table][opportunitystages][mode]}
                                      - uesio/io.box:
                                          uesio.variant: uesio/crm.note
                                          components:
                                            - uesio/io.text:
                                                text: Specify the valid lead sources for your organization. A lead source is where the data for a lead originated.
                                      - uesio/io.box:
                                          uesio.variant: uesio/crm.note
                                          components:
                                            - uesio/io.text:
                                                text: Only active lead sources will appear when selecting a source for a new lead.
