name: public
named: {}
views:
  uesio/crm.login: true
collections: {}
routes:
  uesio/crm.login: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: false
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
